#!/usr/bin/env python3
"""Run the MCN/overlap/density study 100 times, using 75% of available CPU threads."""

import argparse
import os
import json
import shutil
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timezone
from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "examples" / "characterization" / "mcn_overlap_density.yaml"
REPETITIONS = 100


def run_one(config: Path, repetition: int, batch: Path, environment: dict[str, str]) -> tuple[str, int]:
    name = f"mcn_overlap_density_rep_{repetition:03d}"
    destination = batch / name
    command = [
        sys.executable, "-m", "jpgen", str(config),
        "--output-dir", str(destination),
        "--label", name,
        "--experiment", "mcn_overlap_density_characterization",
        "--progress", "none",
    ]
    with (destination / "launch.log").open("w", encoding="utf-8") as log:
        result = subprocess.run(command, cwd=ROOT, env=environment, stdout=log, stderr=subprocess.STDOUT)
    return name, result.returncode


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true", help="Show the workload without starting simulations")
    args = parser.parse_args()

    data = yaml.safe_load(CONFIG.read_text(encoding="utf-8"))
    if data["packing"].get("seed") is not None:
        parser.error("Remove packing.seed so each repetition receives an independent random seed")
    if data["dem"].get("backend_options", {}).get("threads", 1) != 1:
        parser.error("The configuration must use exactly one DEM thread per run")
    from jpgen.packing.configuration import build_packing_plan
    from jpgen.dem.configuration import build_dem_plan
    packing = build_packing_plan(data["packing"])
    dem = build_dem_plan(data["dem"])
    dem.validate_box(packing.box)
    dem.backend.validate(dem)

    available = len(os.sched_getaffinity(0)) if hasattr(os, "sched_getaffinity") else (os.cpu_count() or 1)
    workers = max(1, available * 3 // 4)
    print(f"Available CPU threads: {available}; parallel runs: {workers}; total runs: {REPETITIONS}", flush=True)
    if args.dry_run:
        return 0

    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d_%H-%M-%SZ")
    batch = ROOT / "runs" / "mcn_overlap_density_characterization" / stamp
    batch.mkdir(parents=True, exist_ok=False)
    config = batch / CONFIG.name
    shutil.copyfile(CONFIG, config)
    for repetition in range(1, REPETITIONS + 1):
        (batch / f"mcn_overlap_density_rep_{repetition:03d}").mkdir()
    (batch / "batch.json").write_text(json.dumps({
        "config": config.name, "repetitions": REPETITIONS, "workers": workers,
        "experiment": "mcn_overlap_density_characterization",
        "seeds": "independently generated by JPGen and recorded in each run",
    }, indent=2) + "\n", encoding="utf-8")
    print(f"Results: {batch}", flush=True)

    environment = os.environ.copy()
    environment.update(OMP_NUM_THREADS="1", OPENBLAS_NUM_THREADS="1", MKL_NUM_THREADS="1", PYTHONNOUSERSITE="1")
    failures = []
    with ThreadPoolExecutor(max_workers=workers) as pool:
        futures = [pool.submit(run_one, config, repetition, batch, environment)
                   for repetition in range(1, REPETITIONS + 1)]
        for future in as_completed(futures):
            name, returncode = future.result()
            if returncode:
                failures.append(name)
            print(f"{'FAIL' if returncode else 'OK  '} {name} ({returncode})", flush=True)

    print(f"Completed: {REPETITIONS - len(failures)}; failed: {len(failures)}", flush=True)
    (batch / "completion.json").write_text(json.dumps({
        "completed": REPETITIONS - len(failures), "failed": failures,
    }, indent=2) + "\n", encoding="utf-8")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
